apiVersion: logging.kubesphere.io/v1alpha2
kind: FluentBitConfig
metadata:
  name: fluent-bit-config
  namespace: logging-system
spec:
  filterSelector:
    matchLabels:
      logging.kubesphere.io/enabled: 'true'
  inputSelector:
    matchLabels:
      logging.kubesphere.io/enabled: 'true'
  outputSelector:
    matchLabels:
      logging.kubesphere.io/enabled: 'true'
  service:
    httpListen: 0.0.0.0
    httpPort: 2020
    httpServer: true
    parsersFile: parsers.conf