# permissions for end users to view alertpatterns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alertpattern-viewer-role
rules:
- apiGroups:
  - logging.mesh.hkjc.org.hk
  resources:
  - alertpatterns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - logging.mesh.hkjc.org.hk
  resources:
  - alertpatterns/status
  verbs:
  - get
