# permissions for end users to edit alertpatterns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alertpattern-editor-role
rules:
- apiGroups:
  - logging.mesh.hkjc.org.hk
  resources:
  - alertpatterns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - logging.mesh.hkjc.org.hk
  resources:
  - alertpatterns/status
  verbs:
  - get
