# permissions for end users to view loggings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logging-viewer-role
rules:
- apiGroups:
  - logging.mesh.hkjc.org.hk
  resources:
  - loggings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - logging.mesh.hkjc.org.hk
  resources:
  - loggings/status
  verbs:
  - get
