# permissions for end users to view throttles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: throttle-viewer-role
rules:
- apiGroups:
  - logging.mesh.hkjc.org.hk
  resources:
  - throttles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - logging.mesh.hkjc.org.hk
  resources:
  - throttles/status
  verbs:
  - get
